"""create tablesss

Revision ID: 8f8c9245056c
Revises: 
Create Date: 2023-03-10 20:39:55.052748

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8f8c9245056c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('cost', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('reg_dtime', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('customer',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('reg_dtime', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('dest',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('reg_dtime', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('item',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('cost', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('reg_dtime', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('lease',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('cost', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('reg_dtime', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('machine',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('cost', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('reg_dtime', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('report_detail',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('report_head_id', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('type', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('cost', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('quant', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('unit_type', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('reg_dtime', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_head',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('customer_name', sa.String(length=256), nullable=True),
    sa.Column('worksite_name', sa.String(length=256), nullable=True),
    sa.Column('address', sa.String(length=512), nullable=True),
    sa.Column('memo', sa.String(length=512), nullable=True),
    sa.Column('completed_date', sa.String(length=8), nullable=True),
    sa.Column('reg_dtime', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staff',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('cost', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('reg_dtime', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('trash',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('dest_id', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('name_id', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('cost', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('unit_type', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('reg_dtime', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=256), nullable=True),
    sa.Column('user_pwd', sa.String(length=256), nullable=True),
    sa.Column('user_name', sa.String(length=256), nullable=True),
    sa.Column('reg_dtime', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('auth_type', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('token', sa.String(length=256), nullable=False),
    sa.Column('token_expire_dtime', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('trash')
    op.drop_table('staff')
    op.drop_table('report_head')
    op.drop_table('report_detail')
    op.drop_table('machine')
    op.drop_table('lease')
    op.drop_table('item')
    op.drop_table('dest')
    op.drop_table('customer')
    op.drop_table('car')
    # ### end Alembic commands ###
