version: '3.8'
services:
  web:
    build:
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    ports:
      - "80:8080"
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8443:443"
    volumes:
      # NGINXのコンフィグファイルをホストOSから、ゲストOSに連結する
      - ./default.conf:/etc/nginx/conf.d/default.conf
      # HTTPS用の証明書とキーをホストOSから、ゲストOSに連結する
      - /etc/cert/cert.pem:/etc/nginx/conf.d/cert.pem:Z
      - /etc/cert/secret.key:/etc/nginx/conf.d/secret.key:Z