version: '3.8'
services:
  web:
    container_name: app
    build:
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    ports:
      - "80:8080"
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      # NGINXのコンフィグファイルをホストOSから、ゲストOSに連結する
      - ./default.conf:/etc/nginx/conf.d/default.conf
      # HTTPS用の証明書とキーをホストOSから、ゲストOSに連結する
      - /etc/letsencrypt/live/www.konbumame.com/fullchain.pem:/etc/nginx/conf.d/fullchain.pem:Z
      - /etc/letsencrypt/live/www.konbumame.com/privkey.pem:/etc/nginx/conf.d/privkey.pem:Z
      - ./nginx:/var/www/html
